name: plink2
owner: iuc
description: PLINK is a free, open-source whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner.
homepage_url: https://www.cog-genomics.org/plink/2.0/
remote_repository_url: https://github.com/chrchang/plink-ng
type: unrestricted
categories: 
  - Genome-Wide Association Study
